### ISSUE TITLE
Icons not showing in popup calendar

### ISSUE THREAD

**Issue by adrm** [kekeh/ngx-mydatepicker#31]
The component is working fine, but icons are not loading. I haven't seen any indication about loading some icon library or similar, so I assumed the icons were bundled. I am not using bootstrap, if that could be the cause.

Is it possible to change the source of the icons to avoid depending on bootstrap? Am I missing some step?

Thanks.

![image](https://cloud.githubusercontent.com/assets/307945/25948115/857650d8-3652-11e7-81c6-1d2901c79505.png)

**Comment by kekeh** [comment]
Try to add the following definition to your css file.
```css
.ngxmdp .ngxmdpicon:before { 
    font-family: ngx-mydatepicker !important; 
}
```
