### ISSUE TITLE
db.toggleCalendar() not showing dates to pick

### ISSUE THREAD

**Issue by JosipTomaic** [kekeh/ngx-mydatepicker#79]
I have followed your instructions for implementing this package into an app but when I click on calendar glyphicon dates don't show. Why?
I'm trying to use this package in modal so that could be a problem. I haven't tried to use it in plain .html file.
Thanks!

EDIT:
If I copy and leave code exactly the same then it works. I wanted to adjust html code to suit my .html file.

**Comment by kekeh** [comment]
If you don't see icons try to add the following definition to your css file.
```css
.ngxmdp .ngxmdpicon:before { 
    font-family: ngx-mydatepicker !important; 
}
```
